# Generated by Django 3.0.5 on 2020-04-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_date', models.DateField()),
                ('timetable_start', models.TimeField()),
                ('timetable_name_of_class', models.CharField(max_length=50)),
                ('timetable_idea_of_class', models.TextField()),
            ],
        ),
    ]
